### ISSUE TITLE
Design homescreen logo

### ISSUE THREAD

**Issue by MosesSupposes** [cehsu/sfsbooklet#4]
Here's the link to an article on how to implement this: https://medium.com/dev-channel/designing-a-progressive-web-app-icon-b55f63f9ff6e

Also, here's another helpful article on an online favicon generator that can get you started: http://realfavicongenerator.net/

**Comment by cehsu** [comment]
Great idea @MosesSupposes, perhaps we should consider the SFWAR logo to get started? I bet the UI/UX team members will have some good ideas for this.

**Comment by cehsu** [comment]
Closing for now as this is beyond the scope of the prototype actually (UI). Feel free to work on this separately though as it would be great to do.
